### ISSUE TITLE
用 CSS 实现渐变边框

### ISSUE THREAD

**Issue by yiyang-fairy** [yiyang-fairy/blog#10]
需要实现一个这样的渐变边框

![Image](https://github.com/user-attachments/assets/5bd21e69-65f7-417d-836a-a58a15987fe0)

---
## 方法 1：使用 `border-image`

`border-image` 是一种直接为边框应用渐变的方式。它的优点是简单易用，但需要注意浏览器对 `border-radius` 和 `border-image` 组合的支持情况。

### 实现代码

```css
.box {
    height: 200px;
    width: 500px;
    border-radius: 10px;
    border: 5px solid; /* 设置边框宽度 */
    border-image: linear-gradient(to right, #ff7e5f, #feb47b) 1; /* 渐变边框 */
    background: white; /* 背景色 */
}
```
### 解释
- `border: 5px solid`：设置边框宽度。
- `border-image: linear-gradient(...) 1`：为边框应用线性渐变。
- `background: white`：设置内部背景色。

### 注意事项

- 在某些浏览器中，`border-image` 和 `border-radius` 可能无法完美兼容, 导致`border-radius`不生效

---

## 方法 2：使用伪元素

通过伪元素（如 `::before` 或 `::after`），我们可以创建一个比元素稍大的渐变背景，并将其置于元素下方，从而实现渐变边框效果。

### 实现代码

```css
.box {
    height: 200px;
    width: 500px;
    border-radius: 10px;
    position: relative;
    background: white; /* 内部背景色 */
}

.box::before {
    content: '';
    position: absolute;
    top: -5px; /* 边框宽度 */
    left: -5px; /* 边框宽度 */
    right: -5px; /* 边框宽度 */
    bottom: -5px; /* 边框宽度 */
    background: linear-gradient(to right, #ff7e5f, #feb47b); /* 渐变背景 */
    border-radius: 12px; /* 稍微大一点以覆盖圆角 */
    z-index: -1;
}
```
### 解释
- `::before` 伪元素创建了一个比 `.box` 稍大的渐变背景。
- 通过 `z-index: -1` 将其置于 `.box` 下方。
- `border-radius` 稍微增大以确保圆角效果完美。

 **以上的两种方法 都依赖元素的背景色, 如果想要一个透明背景色的元素渐变边框的话可以使用 `-webkit-mask`**

## 方法 3：使用 `-webkit-mask`

`-webkit-mask` 是一种高级的 CSS 遮罩技术，可以通过遮罩实现复杂的视觉效果，包括渐变边框。
### 实现代码

```css
.box {
    height: 200px;
    width: 500px;
    border-radius: 10px;
    position: relative; /* 为伪元素提供定位基准 */
}

.box::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: linear-gradient(180deg, transparent, #589EFF); /* 边框渐变颜色 */
    border-radius: 0 0 10px 10px; /* 底部圆角 */
    padding: 1px; /* 控制边框宽度 */
  
    -webkit-mask: 
        linear-gradient(#fff 0 0) content-box, /* 第一层遮罩：仅内容区域 */
        linear-gradient(#fff 0 0);            /* 第二层遮罩：整个元素区域 */
    -webkit-mask-composite: xor;              /* 旧版浏览器：异或运算 */
    mask-composite: exclude;                  /* 新版浏览器：排除重叠区域 */
    
    pointer-events: none; /* 禁止伪元素阻挡鼠标事件 */
}
```

### 解释

1. **-webkit-mask 双遮罩**
```css
-webkit-mask: 
    linear-gradient(#fff 0 0) content-box, /* 第一层遮罩：仅内容区域 */
    linear-gradient(#fff 0 0);            /* 第二层遮罩：整个元素区域 */
```
* linear-gradient(#fff 0 0)：
	生成纯白色渐变（起点到终点颜色相同），用于创建全白遮罩层。

* content-box 关键词：
	限定第一个遮罩层仅作用于元素的 内容区域（不包含 padding）。

* 双遮罩层原理：
	第一层遮罩（带 content-box）显示内容区域，第二层遮罩（默认 border-box）显示整个元素区域。通过组合运算后，最终只保留 元素区域减去内容区域 的部分（即边框区域）。

2. **遮罩组合模式**
```css
-webkit-mask-composite: xor;  /* Chrome < 120 */
mask-composite: exclude;      /* 标准属性 */
```
* mask-composite: exclude：
	表示"排除重叠区域"，最终遮罩 = 第二层遮罩 - 第一层遮罩。这样只保留边框区域（内容区域被挖空）。

* -webkit-mask-composite: xor：
	旧版浏览器的等效写法，通过异或运算实现类似效果。

3. 边框宽度控制
```css
padding: 1px;
```
通过 padding 扩大内容区域，结合 content-box 遮罩的特性，padding 值直接控制渐变边框的宽度。

4. 事件穿透
```css
pointer-events: none;
```
禁用伪元素的鼠标事件，使渐变边框不会阻挡下方元素的交互（如点击、悬停）。

---
## 方法对比

|方法|优点|缺点|
|---|---|---|
|`border-image`|简单直接|对 `border-radius` 支持有限|
|伪元素|兼容性好，灵活性强|需要额外代码|
|`-webkit-mask`|高级效果，支持复杂遮罩|兼容性较差|

---

## 总结

实现渐变边框的方法有很多种，每种方法都有其适用的场景和优缺点。前两种方法简单好实现, 但是依赖元素设置背景色, 需要设置好特定的背景色以融入周围环境. 使用 `-webkit-mask` 双遮罩方法不依赖元素背景色, 可复用性更高, 但要注意浏览器兼容性
